name: cd

on:
  workflow_dispatch:
  push:
    tags: [ v-* ]

jobs:
  sam-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
        with:
          version: '1.83.0'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Print version
        run: |
          aws --version
          sam --version
      - name: Build
        run: sam build --use-container
      - name: Deploy
        run: sam deploy --stack-name ${{ secrets.PROJECT_NAME }}
