name: ci

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src/
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test with Gradle
        run: gradle test
